export interface Product {
  id: number;
  name: string;
  category: string;
  origin: string;
  description: string;
  image: string;
  ingredients: string;
  allergenInfo: string;
  nutritionalValues?: {
    [key: string]: string;
  };
  packaging: string;
  storage: string;
  shelfLife: string;
  isVegetarian: boolean;
  isVegan: boolean;
}

export const productsData: Product[] = [
  {
    id: 1,
    name: "Almonds Blanched",
    category: "Nuts",
    origin: "Spain, USA",
    description: "Blanched whole almonds with typical almond flavor, firm and crisp. Creamy white/light beige color. Should not be rancid, mouldy, or bitter.",
    image: "/images/Almonds-Blanched-1.jpg",
    ingredients: "Almond (100%)",
    allergenInfo: "May also contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "612kcal / 2534kj",
      "Protein": "21.1g",
      "Carbohydrates": "6.9g",
      "Sugars": "4.2g",
      "Fat": "55.8g",
      "Saturates": "4.4g",
      "Fibre": "7.4g",
      "Sodium": "0.014g",
      "Salt": "0.035g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 2,
    name: "Almonds Flaked",
    category: "Nuts",
    origin: "Spain",
    description: "Sliced almonds to calibrated thickness with typical almond flavor, firm and crisp, creamy white/beige color, not rancid, mouldy, or bitter.",
    image: "/images/Almonds-Flaked-1.jpg",
    ingredients: "Almond (100%)",
    allergenInfo: "May also contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "612kcal / 2534kj",
      "Protein": "21.1g",
      "Carbohydrates": "6.9g",
      "Sugars": "4.2g",
      "Fat": "55.8g",
      "Saturates": "4.4g",
      "Fibre": "7.4g",
      "Sodium": "0.014g",
      "Salt": "0.035g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 3,
    name: "Almonds Ground",
    category: "Nuts",
    origin: "Spain",
    description: "Mechanically milled blanched almonds, typical almond taste, white/yellow color, not rancid or mouldy.",
    image: "/images/Almonds-Ground-1.jpg",
    ingredients: "Almond (100%)",
    allergenInfo: "May also contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "612kcal / 2534kj",
      "Protein": "21.1g",
      "Carbohydrates": "6.9g",
      "Sugars": "4.2g",
      "Fat": "55.8g",
      "Saturates": "4.4g",
      "Fibre": "7.4g",
      "Sodium": "0.014g",
      "Salt": "0.035g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 4,
    name: "Almonds Nibbed",
    category: "Nuts",
    origin: "Spain",
    description: "Blanched and chopped almonds with typical almond flavour, firm, creamy white/light beige color.",
    image: "/images/Almonds-Nibbed.jpg",
    ingredients: "Almond (100%)",
    allergenInfo: "May also contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "612kcal / 2534kj",
      "Protein": "21.1g",
      "Carbohydrates": "6.9g",
      "Sugars": "4.2g",
      "Fat": "55.8g",
      "Saturates": "4.4g",
      "Fibre": "7.4g",
      "Sodium": "0.014g",
      "Salt": "0.035g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 5,
    name: "Raw Almonds",
    category: "Nuts",
    origin: "USA, Australia",
    description: "Selected shelled almonds, should not be rancid or mouldy.",
    image: "/images/Raw-Almonds.jpg",
    ingredients: "Almond (100%)",
    allergenInfo: "Packed in a factory handling nuts, sesame, gluten, soya & sulphites, stores peanuts.",
    nutritionalValues: {
      "Energy": "575 kcal",
      "Protein": "21g",
      "Carbohydrates": "20g",
      "Fat": "49.4g",
      "Sugars": "4.2g",
      "Fibre": "12.2g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 6,
    name: "Almonds Slivered",
    category: "Nuts",
    origin: "Spain",
    description: "Blanched slivered almonds, stick-shaped pieces, firm, crisp, creamy white color.",
    image: "/images/AFROPOL-FINE-FOODS-SLIVERED-ALMONDS.jpg",
    ingredients: "Almond (100%)",
    allergenInfo: "May also contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "554 kcal",
      "Protein": "21.2g",
      "Carbohydrates": "5.3g",
      "Sugars": "4.5g",
      "Fat": "49.9g",
      "Saturates": "3.8g",
      "Fibre": "12.5g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 7,
    name: "Almonds Smoked",
    category: "Nuts",
    origin: "USA (Smoked in UK)",
    description: "Shelled almonds roasted and flavored with smoke seasoning.",
    image: "/images/Almonds-Smoked.jpg",
    ingredients: "Almonds (96%), Smoke Flavour (4%) (including salt, dextrose, rice flour, dried yeast, sugar, yeast extract powder, smoked paprika, black pepper, onion & garlic powders, natural flavourings, citric acid, anti-caking agent).",
    allergenInfo: "May also contain other nuts, sesame, peanuts*, gluten & sulphites. *Peanuts used on same production line.",
    nutritionalValues: {
      "Energy": "541 kcal",
      "Protein": "20.8g",
      "Carbohydrates": "6.7g",
      "Sugars": "5.3g",
      "Fat": "48g",
      "Saturates": "3.7g",
      "Fibre": "12.1g",
      "Salt": "1.26g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 8,
    name: "Apricots",
    category: "Dried Fruits",
    origin: "Turkey",
    description: "Sun dried apricots, good quality, sulphur added to preserve color & prevent microbial growth.",
    image: "/images/Apricots-Dried.jpg",
    ingredients: "Dried Apricots, Sulphur Dioxide (E220)",
    allergenInfo: "May also contain nuts, sesame & gluten.",
    nutritionalValues: {
      "Energy": "241 kcal",
      "Protein": "3.39g",
      "Carbohydrates": "62.64g",
      "Sugars": "53.44g",
      "Fat": "0.51g",
      "Fibre": "7.3g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 9,
    name: "Banana Chips",
    category: "Dried Fruits",
    origin: "Philippines",
    description: "Saba banana slices lightly fried in coconut oil, dipped in sugar solution. Crunchy and firm with characteristic banana flavor.",
    image: "/images/Banana-Chips.jpg",
    ingredients: "Fresh peeled bananas 55%, coconut oil 26%, sugar refined 18.97%, natural banana flavour 0.03%.",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "505 kcal",
      "Protein": "2.94g",
      "Carbohydrates": "47.06g",
      "Sugars": "29.41g",
      "Fat": "26.47g",
      "Saturates": "26.47g",
      "Fibre": "5.9g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 10,
    name: "Blue Poppy Seeds",
    category: "Seeds",
    origin: "Czech Republic, the Netherlands, Australia",
    description: "Very small crunchy poppy seeds, grey-blue in color, characteristic poppy seed odor and flavor without off-flavors.",
    image: "/images/Blue-Poppy-Seeds.jpg",
    ingredients: "Blue Poppy Seeds (100%)",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "525 kcal / 2196 kj",
      "Protein": "17.99 g",
      "Carbohydrates": "28.13 g",
      "Sugar": "2.99 g",
      "Fat": "41.56 g",
      "Saturates": "4.51 g",
      "Fibre": "19.5 g",
      "Sodium": "0.026 g",
      "Salt": "0.065 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 11,
    name: "Brazil Nuts",
    category: "Nuts",
    origin: "Bolivia, Peru",
    description: "Selected clean, sound shelled brazil nuts with consistent size. Crisp texture, characteristic flavor, pale yellow/brown color.",
    image: "/images/Brazil-Nuts.jpg",
    ingredients: "Brazil nuts (100%)",
    allergenInfo: "May also contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "682 kcal",
      "Protein": "14.1 g",
      "Carbohydrates": "3.1 g",
      "Sugars": "2.4 g",
      "Fat": "68.2 g",
      "Saturates": "16.4 g",
      "Fibre": "4.3 g",
      "Sodium": "0.003 g",
      "Salt": "0.0075 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 12,
    name: "Cashews Broken",
    category: "Nuts",
    origin: "India, Vietnam, Brazil",
    description: "Obtained through roasting and shelling, light yellow to pale ivory color, free from foreign odours/flavours.",
    image: "/images/Cashews-Broken.jpg",
    ingredients: "Cashews (100%)",
    allergenInfo: "May contain other nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "573 kcal",
      "Protein": "17.7 g",
      "Carbohydrates": "18.1 g",
      "Sugars": "4.6 g",
      "Fat": "48.2 g",
      "Saturates": "9.5 g",
      "Fibre": "3.2 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 13,
    name: "Roasted Salted Cashews",
    category: "Nuts",
    origin: "Vietnam (Roasted and salted in UK)",
    description: "Obtained through roasting and salting, consistent shape.",
    image: "/images/Roasted-Salted-Cashews.jpg",
    ingredients: "Cashews Nuts (94%), Rapeseed oil, Salt.",
    allergenInfo: "Packed in factory handling nuts, sesame, gluten, soya & sulphites and stores peanuts.",
    nutritionalValues: {
      "Energy": "609 kcal",
      "Protein": "17.7 g",
      "Carbohydrates": "29 g",
      "Sugars": "4.9 g",
      "Fat": "46.3 g",
      "Saturates": "9 g",
      "Fibre": "2.9 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 14,
    name: "Whole Cashews",
    category: "Nuts",
    origin: "India, Vietnam, Brazil",
    description: "Obtained through roasting and shelling, consistent shape with less than 1/8 broken kernels.",
    image: "/images/Whole-Cashews.jpg",
    ingredients: "Cashews (100%)",
    allergenInfo: "Packed in factory handling nuts, sesame, gluten, soya & sulphites and stores peanuts.",
    nutritionalValues: {
      "Energy": "574 kcal",
      "Protein": "15.31 g",
      "Carbohydrates": "32.6 g",
      "Sugars": "4.6 g",
      "Fat": "46.35 g",
      "Saturates": "9.15 g",
      "Fibre": "3 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 15,
    name: "Cherries",
    category: "Dried Fruits",
    origin: "Poland",
    description: "High-quality fresh sour cherries (mainly Lutowka variety), washed, pitted, IQF frozen, osmotically dehydrated in apple concentrate, dried, inspected, sunflower oil added to prevent clumping.",
    image: "/images/Cherries.jpg",
    ingredients: "Sour Cherry (~80%), Apple Juice Concentrate (~19%), Sunflower Oil (~1%).",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "332 kcal",
      "Protein": "2.1 g",
      "Carbohydrates": "75.6 g",
      "Sugars": "72.3 g",
      "Fat": "0.3 g",
      "Saturates": "<0.1 g",
      "Fibre": "5.3 g",
      "Sodium": "0.0049 g",
      "Salt": "0.012 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 16,
    name: "Chia Seeds",
    category: "Seeds",
    origin: "Peru, Bolivia, Argentina",
    description: "High in essential fatty acids, antioxidants, vitamins and minerals, soluble fiber; gluten-free, suitable for celiacs.",
    image: "/images/Chia-Seeds.jpg",
    ingredients: "Chia Seeds (100%)",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "486 kcal",
      "Protein": "16.54 g",
      "Carbohydrates": "42.12 g",
      "Sugars": "0 g",
      "Fat": "30.74 g",
      "Saturates": "3.3 g",
      "Fibre": "34.4 g",
      "Salt": "0.04 g",
      "Sodium": "16 mg"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry, ambient conditions.",
    shelfLife: "6+ months",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 17,
    name: "Coconut Desiccated Fine",
    category: "Specialty Items",
    origin: "Sri Lanka, Indonesia, Philippines, Vietnam",
    description: "De-shelled, washed, blanched, grated, dried, sieved, hygienically packed fine grade desiccated coconut. White in colour, free from yellow specks or discoloration. Unsweetened.",
    image: "/images/Coconut-Desiccated-Fine.jpg",
    ingredients: "Fine Desiccated Coconut (unsweetened)",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "604 kcal / 2492 kj",
      "Protein": "5.6 g",
      "Carbohydrates": "6.4 g",
      "Sugars": "6.4 g",
      "Fat": "62 g",
      "Saturates": "53.4 g",
      "Fibre": "13.7 g",
      "Sodium": "0.028 g",
      "Salt": "0.07 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 18,
    name: "Coconut Raw Chips",
    category: "Specialty Items",
    origin: "Sri Lanka, Indonesia, Philippines",
    description: "Raw, unsweetened, flat brittle coconut strips with free-flowing texture. White to cream colour with no off-flavours.",
    image: "/images/Coconut-Raw-Chips.jpg",
    ingredients: "Raw unsweetened chip coconut",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "604 kcal / 2492 kj",
      "Protein": "5.6 g",
      "Carbohydrates": "6.4 g",
      "Sugars": "6.4 g",
      "Fat": "62 g",
      "Saturates": "53.4 g",
      "Fibre": "13.7 g",
      "Sodium": "0.028 g",
      "Salt": "0.07 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 19,
    name: "Coconut Toasted Chips",
    category: "Specialty Items",
    origin: "Sri Lanka, Indonesia, Philippines",
    description: "Toasted, unsweetened desiccated coconut, shredded and dried. Cream to golden brown color, free from discoloration.",
    image: "/images/Coconut-Toasted-Chips.jpg",
    ingredients: "Toasted unsweetened coconut (100%)",
    allergenInfo: "May also contain nuts, sesame, gluten & sulphites.",
    nutritionalValues: {
      "Energy": "604 kcal / 2492 kj",
      "Protein": "5.6 g",
      "Carbohydrates": "6.4 g",
      "Sugars": "6.4 g",
      "Fat": "62 g",
      "Saturates": "53.4 g",
      "Fibre": "13.7 g",
      "Sodium": "0.028 g",
      "Salt": "0.07 g"
    },
    packaging: "Primary: BRC certified food grade bag (70 micron thickness). Outer: Recyclable corrugated double-walled brown box (375 x 240 x 325mm). Gross weight: 1.012kgs; Net weight: 1kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  },
  {
    id: 20,
    name: "Cous Cous Giant",
    category: "Grains",
    origin: "Israel or Italy",
    description: "Circular grain balls of regular shape, creamy colour, free from off flavour and odour.",
    image: "/images/Cous-Cous-Giant.jpg",
    ingredients: "Wheat Flour (100%)",
    allergenInfo: "May also contain nuts, sesame & sulphites.",
    nutritionalValues: {
      "Energy": "361 kcal",
      "Protein": "10 g",
      "Carbohydrates": "77 g",
      "Sugars": "2 g",
      "Fat": "1.1 g",
      "Saturates": "0 g",
      "Fibre": "3 g",
      "Sodium": "0.04 g",
      "Salt": "0.1 g"
    },
    packaging: "Primary packaging: BRC certified food grade bag; Outer: corrugated box (375x240x325mm). Net weight 5kg.",
    storage: "Cool, dry area free from contamination and moisture.",
    shelfLife: "Minimum 6 months from pack date",
    isVegetarian: true,
    isVegan: true
  }
];